### PR TITLE
Custom cache file location

### PR DESCRIPTION
**Pull request by NigoroJr**
This implements the change proposed in b4b4r07/zplug#119.

### CODE REVIEW

**Comment by NigoroJr** [comment]
Hmm... Travis says:

```
__zplug::zplug::cache::update:11: no such file or directory: 
```

but this doesn't happen in my environment. I wonder why?

**Comment by babarot** [comment]
https://github.com/b4b4r07/zplug2/blob/master/lib/zplug/cache.zsh#L65-L97

There are a lot of suspicious records.

**Comment by NigoroJr** [comment]
I executed the _exact_ same commands as Travis and didn't get the error message...

``` console
$ git clone --depth=1 https://github.com/b4b4r07/zplug2.git b4b4r07/zplug2
$ cd b4b4r07/zplug2
$ git fetch origin +refs/pull/23/merge:
$ git checkout -qf FETCH_HEAD
$ make test
[13:45:29] ./test/autoload/commands/__check___test.zsh   ......
[13:45:29] ./test/autoload/commands/__clean___test.zsh   ........
[13:45:29] ./test/autoload/commands/__clear___test.zsh   ....
[13:45:33] ./test/autoload/commands/__install___test.zsh .......
[13:45:33] ./test/autoload/commands/__list___test.zsh    ............
[13:45:35] ./test/autoload/commands/__load___test.zsh    .....
[13:45:35] ./test/autoload/commands/__status___test.zsh  ..
[13:45:35] ./test/autoload/commands/__update___test.zsh  ..
[13:45:35] ./test/autoload/options/__help___test.zsh     ..
[13:45:35] ./test/autoload/options/__version___test.zsh  ..
[13:45:35] ./test/autoload/utils/__add___test.zsh        .....
[13:45:35] ./test/autoload/utils/__arguments___test.zsh  .....
[13:45:35] Finished in 6.602455 seconds
```

So I guess it's safe to merge? :confused:

**Comment by babarot** [comment]
Hmm, this looks like safety to me.

**Comment by babarot** [comment]
Merged

**Comment by NigoroJr** [comment]
Thank you!

**Pull request merged**
