### PR TITLE
Fix version check of git

### PR DESCRIPTION
**Pull request by NigoroJr**
This change is exactly the same as b4b4r07/zplug#103.

### CODE REVIEW

**Comment by NigoroJr** [comment]
@b4b4r07 I added some test cases for `__git_version` but for some reason `make test` is failing for pretty much all the cases. I don't know why this happens because Travis is clearly working. ~~I will try to fix this local issue and push the test cases, so please wait merging this PR in the meantime :bow:~~

Update: Cloning a fresh copy of this repository and running `make test` also fails. Now I don't know why Travis is not failing... :dizzy_face: 

Update2: Tests run fine without any problem on my Mac. I tested out with two Gentoo Linux machines and they both fail.

**Comment by babarot** [comment]
Thank you @NigoroJr 

I came up with `command` command is the best workaround. What do you think? Of course, I think your approach is good idea.

**Comment by NigoroJr** [comment]
@b4b4r07 ~~I think the issue isn't so much aliasing `git` to `hub` but the fact that `git --version` outputs a string in the form `git version 2.7.0`, but the match `${(M)${(z)"$(git --version)"}:#[0-9]*[0-9]}` is done under the assumption that the output from `git --version` starts with a number.~~

Update: It might very well just be a quoting issue. Nested double quotes in `"${(M)${(z)"$(git --version)"}:#[0-9]*[0-9]} "` looks fishy to me. Trying out:

```
# This works
$ print ${(M)${(z)"$( git --version )"}:#[0-9]*[0-9]}
2.7.0
# but this doesn't work
$ print "${(M)${(z)"$( git --version )"}:#[0-9]*[0-9]}"
$
```

What do you think?

**Comment by NigoroJr** [comment]
~~I guess now that I think about it, using `%` rather than `#` would work in this case, too. Do you think `%` is better?~~ See comment above.

**Comment by babarot** [comment]
Oh..., `print ${(M)${(z)"$( git --version )"}:#[0-9]*[0-9]}` is correct.  This is my bad :sob:

**Comment by NigoroJr** [comment]
@b4b4r07 That's fine! I updated and rebased that change. How does it look? Also, I wasn't sure if the tests look okay or not.

**Comment by babarot** [comment]
Looks good to me. And your tests are no prob, too. Merging.

BTY, I'm planning to convert all `lib` files into autoload files because, this issue may be so, but I recognize that the problems of aliases are troublesome. However, by using autoload-ize, we can avoid this matter.

Like this:
- `lib/core/core.zsh` -> `lib/core/__core.zsh`
- `__import() { autoload -Uz __core.zsh; __core.zsh }`
- use `__foobar` in __core.zsh file

**Comment by NigoroJr** [comment]
Okay, thanks :+1: Hmm... I don't quite get the usage just from that example, but I see there can be potential problems with aliases. I'll keep an eye on future commits.

**Pull request merged**
